/* Generated By:JavaCC: Do not edit this line. FormulaParserLL3Constants.java */
package org.sbml.jsbml.text.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormulaParserLL3Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 3;
  /** RegularExpression Id. */
  int DIGIT = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int EXPNUMBER = 6;
  /** RegularExpression Id. */
  int SLPITTER = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int POWER = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int TIMES = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int OPEN_PAR = 13;
  /** RegularExpression Id. */
  int CLOSE_PAR = 14;
  /** RegularExpression Id. */
  int COMPARISON = 15;
  /** RegularExpression Id. */
  int BOOLEAN_LOGIC = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int XOR = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int LOG = 21;
  /** RegularExpression Id. */
  int STRING = 22;
  /** RegularExpression Id. */
  int IDCHAR = 23;
  /** RegularExpression Id. */
  int LETTER = 24;
  /** RegularExpression Id. */
  int EOL = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<INTEGER>",
    "<DIGIT>",
    "<NUMBER>",
    "<EXPNUMBER>",
    "<SLPITTER>",
    "\"+\"",
    "\"^\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<COMPARISON>",
    "<BOOLEAN_LOGIC>",
    "<AND>",
    "<OR>",
    "<XOR>",
    "<NOT>",
    "\"log\"",
    "<STRING>",
    "<IDCHAR>",
    "<LETTER>",
    "<EOL>",
  };

}
