/* Generated By:JavaCC: Do not edit this line. TextToASTNodeParserConstants.java */
package org.sbml.jsbml.text.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TextToASTNodeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int INTEGER = 4;
  /** RegularExpression Id. */
  int EXPNUMBER = 5;
  /** RegularExpression Id. */
  int FUNCTION = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int POWER = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int TIMES = 10;
  /** RegularExpression Id. */
  int DIVIDE = 11;
  /** RegularExpression Id. */
  int OPEN_PAR = 12;
  /** RegularExpression Id. */
  int CLOSE_PAR = 13;
  /** RegularExpression Id. */
  int EOL = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<NUMBER>",
    "<INTEGER>",
    "<EXPNUMBER>",
    "<FUNCTION>",
    "\"+\"",
    "\"^\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<EOL>",
  };

}
