/* Generated By:JavaCC: Do not edit this line. TextToASTNodeParserConstants.java */
package org.sbml.jsbml.text.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TextToASTNodeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int INTEGER = 4;
  /** RegularExpression Id. */
  int EXPNUMBER = 5;
  /** RegularExpression Id. */
  int STRING = 6;
  /** RegularExpression Id. */
  int SLPITTER = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int POWER = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int TIMES = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int LOG = 13;
  /** RegularExpression Id. */
  int FACULTY = 14;
  /** RegularExpression Id. */
  int OPEN_PAR = 15;
  /** RegularExpression Id. */
  int CLOSE_PAR = 16;
  /** RegularExpression Id. */
  int COMPARISON = 17;
  /** RegularExpression Id. */
  int EOL = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<NUMBER>",
    "<INTEGER>",
    "<EXPNUMBER>",
    "<STRING>",
    "<SLPITTER>",
    "\"+\"",
    "\"^\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"log\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "<COMPARISON>",
    "<EOL>",
  };

}
