package org.sbml.jsbml.validator.factory;


public enum CheckCategory 
{
  GENERAL,
  CONSISTENCY,
  MATH,
  PACKAGE,
  COMPATIBILITY_L1_V1,
  COMPATIBILITY_L1_V2,
  COMPATIBILITY_L2_V1,
  COMPATIBILITY_L2_V2,
  COMPATIBILITY_L2_V3,
  COMPATIBILITY_L2_V4,
  COMPATIBILITY_L3_V1
}
